#!/usr/bin/env python3
import os
from datetime import datetime
import sys
import subprocess

def save_report(content):
    os.makedirs("/tmp/netdoctor-reports", exist_ok=True)

    filename = datetime.now().strftime("report-%Y-%m-%d-%H-%M-%S.txt")
    path = f"/tmp/netdoctor-reports/{filename}"

    with open(path, "w") as f:
        f.write(content)

    print(f"\n[REPORT SAVED] {path}")

def run(cmd):
    return subprocess.run(
        cmd,
        shell=True,
        capture_output=True,
        text=True
    ).stdout.strip()

def ok(msg):
    print(f"[OK]  {msg}")

def fail(msg):
    print(f"[FAIL] {msg}")

def print_section(title):
    print("\n=== " + title + " ===\n")

def check_service(name, port):
    result = run(f"ss -tulpn | grep {port}")
    if result:
        ok(f"{name} is running (port {port})")
    else:
        fail(f"{name} not running (port {port})")

mode = "full"

if len(sys.argv) > 1:
    mode = sys.argv[1]


print("NETDOCTOR v2\n")

if mode == "quick":
    print_section("QUICK CHECK")

    ip = run("ip route get 1.1.1.1 | awk '{print $7; exit}'")
    ok(f"Local IP: {ip}")

    internet = run("ping -c 1 8.8.8.8")
    if "1 received" in internet:
        ok("Internet reachable")
    else:
        fail("Internet NOT reachable")

    sys.exit(0)

if mode == "report":
    output = ""

    output += "NETDOCTOR REPORT\n\n"

    output += "SYSTEM INFO\n"
    output += run("hostname") + "\n"
    output += run("uname -r") + "\n\n"

    output += "NETWORK\n"
    output += run("ip a") + "\n\n"

    output += "OPEN PORTS\n"
    output += run("ss -tulpn") + "\n"

    save_report(output)
    sys.exit(0)

# ---------------- FULL MODE ----------------
print_section("SYSTEM INFO")

print("Hostname:", run("hostname"))
print("Kernel:", run("uname -r"))


print_section("NETWORK")

ip = run("ip route get 1.1.1.1 | awk '{print $7; exit}'")
gw = run("ip route | awk '/default/ {print $3}'")

print("Local IP:", ip)
print("Gateway:", gw)


print_section("DNS TEST")

dns = run("getent hosts google.com")
if dns:
    ok("DNS working")
else:
    fail("DNS failure")


print_section("INTERNET TEST")

ping = run("ping -c 1 8.8.8.8")
print("Internet:", "OK" if "1 received" in ping else "FAIL")


print_section("OPEN PORTS")

ports = run("ss -tulpn | grep LISTEN")

if ports:
    print(ports)
else:
    fail("No listening ports found")

print_section("SERVICE CHECKS")

check_service("SSH", "22")
check_service("HTTP", "80")
check_service("HTTPS", "443")
